### ISSUE TITLE
Show Original and Reaction Videolength

### ISSUE THREAD

**Issue by Manue3pii** [Streamfinity/Extension#97]
As a viewer, would it be pretty cool to see the video length of the original video and the video's reaction. Maybe in this format HH:MM:SS (HH:MM:SS).

Currently I need to click on the thumbnail to get to the original video, check the length and then click on the stream and figure out on my own how long they took to watch the video. That's a bit annoying

**Comment by romanzipp** [comment]
Thanks for the suggestion! I've added a duration badge to the thumbnail which shows the video length. Will be released in the next minor update.
![Screenshot 2024-06-28 at 16 26 31](https://github.com/Streamfinity/Extension/assets/11266773/8e5b903a-ed5c-477f-8719-2c81cbdb91a7)
